# Generated by Django 5.0.7 on 2024-07-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='uploader',
        ),
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
